name: code_generate
description: generate required codes

runs:
  using: composite
  steps:
  - uses: actions/cache@v2
    id: generated-code-cache
    with:
      key: generated_code@${{ github.sha }}
      path: |
        packages/bff/src/resolvers/_generated.ts
        packages/frontend/node_modules/@chakra-ui/styled-system/dist/declarations/src/theming.types.d.ts
        packages/frontend/src/hooks/api/_generated_gql_codes.ts
        packages/frontend/src/libs/$path.ts
        packages/frontend/src/test_utils/mocks/_generated_gql_mocks.ts
        packages/frontend/src/libs/urql/_generated_gql_schema_json.ts
  - shell: bash
    name: generate code
    run: |
      if [ "${{ steps.generated-code-cache.outputs.cache-hit }}" = 'true' ]; then
        exit
      fi

      cd packages/bff
      pnpm dev &
      bff_server_pid=$!

      wait_count=0
      until `ss -ntl | grep 4000 >/dev/null`; do
        echo "Wait for start server" && sleep 1 && wait_count=`expr ${wait_count} + 1`
        [ ${wait_count} -eq 30 ] && exit 1
      done

      cd ../frontend
      export GRAPHQL_URL_FOR_CODEGEN=http://localhost:4000/graphql
      pnpm gen

      kill ${bff_server_pid}

